category:
  label: 分类设置
  items:
    news_category_slug:
      name: news_category_slug
      label: 新闻公告
      type: text
      data-type: string
      default: news
      placeholder: 请输入公告通知分类的别名
      description: 首页「最新公告」模块展示该分类下的文章
    beginner_category_slug:
      name: beginner_category_slug
      label: 新手指引
      type: text
      data-type: string
      default: beginner
      placeholder: 请输入新手指引分类的别名
      description: 首页「新手指引」模块展示该分类下的文章
